// loading and UI
export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING' 
export const START_SUBMITTING = 'START_SUBMITTING'
export const STOP_SUBMITTING = 'STOP_SUBMITTING'
export const GET_RANDOM_LOADING_TEXT = 'GET_RANDOM_LOADING_TEXT'
export const SET_LOADING_TEXT = 'SET_LOADING_TEXT'
export const SET_LOADING_TEXT_INTERVAL_KEY = 'SET_LOADING_TEXT_INTERVAL_KEY'
export const SET_LOADING_TEXT_OPTIONS = 'SET_LOADING_TEXT_OPTIONS'
export const TAKE_DELAYED_SCREENSHOT = 'TAKE_DELAYED_SCREENSHOT'

// cart
export const SET_AVAILABLE_PRODUCTS = 'SET_AVAILABLE_PRODUCTS'